### ISSUE TITLE
Frame could not be processed

### ISSUE THREAD

**Issue by Mr-Kyrie** [jzhzhang/ROSEFusion#1]
I downloaded the seq file and related configuration files,but it could run the programe with a small size synthesis seq file and related configuration files in github. The erro information shows "Frame could not be processed" and every frame all like this,so I don't know how to fit the bug.

**Comment by jzhzhang** [comment]
@Mr-Kyrie  Please share more details, like the .seq and related configuration files you used.  
As a quick suggestion, you can try the [example](https://drive.google.com/drive/folders/1vW5GV2xsJN1kIrl-5JZX1fUrpjCtp5AS?usp=sharing)  to make sure your program is installed correctly.

**Comment by Mr-Kyrie** [comment]
I just use the link of example about .seq and related configuration files and run the&nbsp;./ROSEFsuion with you config file and .seq.However, only depth map and color map are displayed in the running process, and the number of vertex of the point cloud is 0. The output information of the command line is "frame is not processed".So I don't know how to solve it.Please give me some advice,thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jzhzhang/ROSEFusion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月16日(星期五) 晚上8:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jzhzhang/ROSEFusion] Frame could not be processed (#1)





 
@Mr-Kyrie  Please share more details, like the .seq and related configuration files you used.
 As a quick suggestion, you can try the example  to make sure your program is installed correctly.

**Comment by jzhzhang** [comment]
Do you check the version of CUDA and OpenCV? 
- OpenCV with CUDA ( v4.5.0)
- CUDA (11.0 , 11.1) 
I only test the code with rtx 2080 SUPER and rtx 3080 in ubuntu 16.04.

**Comment by Mr-Kyrie** [comment]
I use OpenCV with CUDA(v4.5.0) and not with sfm module and python 2 and 3,because it always occure erros.
CUDA is 11.0,code with 1080.
May I add your wechat for&nbsp;facilitateing follow-up communication?My wechat is lw574970565.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jzhzhang/ROSEFusion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月16日(星期五) 晚上9:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jzhzhang/ROSEFusion] Frame could not be processed (#1)





 
Do you check the version of CUDA and OpenCV?
  
OpenCV with CUDA ( v4.5.0)
 
CUDA (11.0 , 11.1)
 I only test the code with rtx 2080 SUPER and rtx 3080 in ubuntu 16.04.

**Comment by rlczddl** [comment]
@Mr-Kyrie how to solve? i meet the same problem.

**Comment by renhaofan** [comment]
I meet the same problem with Docker on example dataset
