### ISSUE TITLE
 "run_example.sh" and "run_stairwell.sh"

### ISSUE THREAD

**Issue by ronaldpan** [jzhzhang/ROSEFusion#11]
Could you please put the  "run_example.sh" and "run_stairwell.sh" files in github?

**Comment by jzhzhang** [comment]
Some parameters of the configuration files like `PST_path`, `result_path` should be modified based on your own environment.  The docker image has already been correctly set up, so it's easy to prepare the *.sh for a quick start.

If you want to run ROSEFusion under your own environment, you have to make sure all the parameters in the configuration files are correct. After that, you can run the command below:
`./ROSEFsuion  example_camera.yaml example_data.yaml example_controller.yaml`

You can download the `.seq` and the `.yaml` from [google driver](https://drive.google.com/drive/folders/1vW5GV2xsJN1kIrl-5JZX1fUrpjCtp5AS?usp=sharing)
