### ISSUE TITLE
Camera drift after loop closure

### ISSUE THREAD

**Issue by ronaldpan** [jzhzhang/ROSEFusion#14]
I try a slow speed sequence and find camera drift after loop closure. Is there any method to solve this problem?
![屏幕截图 2022-01-16 172133](https://user-images.githubusercontent.com/13417382/149654497-616dd411-bd10-4a64-9a44-79ff052676e4.jpg)

**Comment by jzhzhang** [comment]
The ROSEFusion only takes the depth for camera tracking. There is no direct way to solve the loop closure based on ROSEFusion.

Here are some quick tips that may improve the quality of the reconstruction: 
1) you can use a smaller voxel size 
2) using a depth sensor with higher quality depth map.

**Comment by ronaldpan** [comment]
I think it is due to no global pose optimization in ROSEFusion.

**Comment by jzhzhang** [comment]
The ROSEFusion currently only considers the relative motion between consecutive frames. Admitting RGB images for global optimization might solve this problem as you mentioned.

**Comment by tangqi1012** [comment]
Hello, is this your own data set for testing? How do you generate PST file?
