### ISSUE TITLE
How can I use the project with my depth camera online?

### ISSUE THREAD

**Issue by calmelo** [jzhzhang/ROSEFusion#15]
Can I use the project with my depth camera online? Your example is a dataset, and we must organize our data as the format the project needed. Can the project be used with a depth camera online or just a rosbag? If you can provide the method of using the project with a camera, I will be very grateful！

**Comment by jzhzhang** [comment]
Currently, we do not have a plan to open source the online reconstruction code. You can integrate the related camera SDK within the [main.cpp](https://github.com/jzhzhang/ROSEFusion/blob/main/src/main.cpp#L78).
