### ISSUE TITLE
Do I need to recreate PST for my own data?

### ISSUE THREAD

**Issue by pandahops1** [jzhzhang/ROSEFusion#16]
In the paper you mentioned:
> PST is a set of particles pre-sampled uniformly within the unit sphere in the 6D space of camera pose. Through moving and rescaling the pre-sampled PST guided by swarm intelligence, our method is able to drive tens of thousands of particles to locate and cover a good local optimum extremely fast and robustly.

It seems that the .tiff files are just a uniform sampling of poses in 6D space. But in readme.md you said:

> You can find the .tiff images in [PST dicrectory](https://github.com/jzhzhang/ROSEFusion/blob/main/PST), and please replace the PST path in controller_config.yaml with your own path.

Shoud I create my own PST? Thanks.

**Comment by pandahops1** [comment]
#10 ok it seems like its answered here.

**Comment by xiaopeige** [comment]
How to generate PST, I don't know how to generate，，thank you

**Comment by jzhzhang** [comment]
@xiaopeige 
We use the Poisson-disk sampling to generate the PST within a unit sphere. And the particles within the PST range from -1 to 1. 

You can adapt to other uniform sampling strategies for simplification, like FPS or voxel sampling.

**Comment by xiaopeige** [comment]
> @xiaopeige We use the Poisson-disk sampling to generate the PST within a unit sphere. And the particles within the PST range from -1 to 1.
> 
> You can adapt to other uniform sampling strategies for simplification, like FPS or voxel sampling.

Sorry, I still don't know how to generate PST, do you have relevant examples or references? thank you

**Comment by tangqi1012** [comment]
> > @xiaopeige We use the Poisson-disk sampling to generate the PST within a unit sphere. And the particles within the PST range from -1 to 1.
> > You can adapt to other uniform sampling strategies for simplification, like FPS or voxel sampling.
> 
> Sorry, I still don't know how to generate PST, do you have relevant examples or references? thank you

Hello, do you know how to generate PST  now？
