### ISSUE TITLE
Reconstruction range

### ISSUE THREAD

**Issue by Goughhhhhh** [jzhzhang/ROSEFusion#18]
When I run ROSEFusion in a room, suddenly the 3D shaded map in the Panglin window disappeared, like this
![2022-03-03 22-29-23屏幕截图](https://user-images.githubusercontent.com/52019760/156586505-57d4cd5a-6b36-4cbd-bc78-c6a1c5ec7b39.png)
And the console warning "Frame could not be processed", 
![2022-03-03 22-34-35屏幕截图](https://user-images.githubusercontent.com/52019760/156586852-6d73375e-4ac3-4d29-8f95-623214e77a9f.png)
WHY??? I guess because of the camera is out of the reconstruction range. What is the unit of the "voxel_size" in dateset_config？Millimeter？

**Comment by jzhzhang** [comment]
The voxels are measured in millimeters. You can try using larger voxels to ensure the volume contains the whole scene.

**Comment by Goughhhhhh** [comment]
@jzhzhang  Thanks for your suggestion,  I tried using a larger volume size( voxel_x: 1012, voxel_y: 412. voxel_z: 612.), the range of reconstruction has indeed increased, but also out of the range in a big meeting room. If I continue to increase the volume size, the console warning "Segmentation fault core dump", I guess the set volume size is over the threshold of the max size. So, what is the maximum volume size allowed by ROSEFusion?

> The voxels are measured in millimeters. You can try using larger voxels to ensure the volume contains the whole scene.

**Comment by jzhzhang** [comment]
The maximum resolution (voxel_x/y/z) of volume depends on the memory of your graphics card. Another quick solution is to adjust the size of voxels  (e.g. 30 mm ) to obtain a larger volume.

**Comment by Goughhhhhh** [comment]
@jzhzhang  I see, thank you very much!

> The maximum resolution (voxel_x/y/z) of volume depends on the memory of your graphics card. Another quick solution is to adjust the size of voxels (e.g. 30 mm ) to obtain a larger volume.
