### ISSUE TITLE
Depth cameras support

### ISSUE THREAD

**Issue by vtushevskiy** [jzhzhang/ROSEFusion#2]
Have you tested it on another cameras like Intel RealSense?

**Comment by jzhzhang** [comment]
We have evaluated ROSEFusion with TUM dataset (captured by Kinect), ETH3D (Asus Xtion Live Pro), FastCaMo-Real (Azure Kinect) and [BundleFusion dataset](https://graphics.stanford.edu/projects/bundlefusion/#data) (structure sensor).  Just make sure that the depth map from your depth sensor contains good geometry information.
