### ISSUE TITLE
Frame could not be processed when running example

### ISSUE THREAD

**Issue by wuqs-net** [jzhzhang/ROSEFusion#21]
Hello, I'm using a GTX 1050 Ti (with CUDA 11.6) to run the program with the example data set. I have updated CMakeLists.txt accordingly and changed the PST path in the config file. But I still got the following output when running:

```
n:0
n:1
Frame could not be processed
n:2
Frame could not be processed
n:3
Frame could not be processed
```

The window displayed the frames correctly, but the output PLY does not contain any vertex.

**Comment by jzhzhang** [comment]
Can you provide more details about your environment? This mistake is highly related to your environment or GPU configuration.

**Comment by wuqs-net** [comment]
Thanks for your response! My environment is

GPU: GTX 1050 Ti (compute capability 6.1, I have changed to this in CMakeLists.txt)
Ubuntu 20.04
CUDA 11.6
OpenCV 4.5.5
Eigen 3.3.9
Pangolin 0.6

I'm running with `example_camera.yaml`, `example_controller.yaml`, `example_data.yaml`, and `example.seq`.

I have run the example on docker successfully. But I couldn't make it work in my own environment.

**Comment by wuqs-net** [comment]
Update:
I created my own docker image with CUDA 11.1.1 and the example ran successfully on it. CUDA 11.6 with other configurations unchanged did not work. The problem is probably related to CUDA version.

**Comment by jzhzhang** [comment]
I also tested with CUDA 11.4, and it worked. I guess the problem may relate to the CUDA version or any other libs, which is also mentioned in [issue 20 ](https://github.com/jzhzhang/ROSEFusion/issues/20).

Anyway, I will mark this issue for future investigation.

**Comment by hpf9017** [comment]
大佬，你好
我的环境，ubuntu 20.04  cuda11.4 opencv-4.5.0  ceres1.14
跑example.seq，但是结果还是Frame could not be processed

**Comment by njk378390126** [comment]
> 大佬，你好 我的环境，ubuntu 20.04 cuda-11.4 opencv-4.5.0 ceres1.14 ，eigen3.3.7, 显卡rtx2060，算力7.5，都相应的改了 跑example.seq，但是结果还是Frame could not be processed

你好，我也遇到了同样的问题。我在3070显卡上不论是自己配置环境还是使用docker都有这个报错。但是切换到2080的机器上就没有这个问题了。问题应该在cuda那块。

**Comment by njk378390126** [comment]
> 大佬，你好 我的环境，ubuntu 20.04 cuda-11.4 opencv-4.5.0 ceres1.14 ，eigen3.3.7, 显卡rtx2060，算力7.5，都相应的改了 跑example.seq，但是结果还是Frame could not be processed

在作者提醒下我解决了问题，最终发现3070的算力应该设成86。你把eigen和cuda版本，切换成3.3.9和11.1会成功吗

**Comment by JoennyChow** [comment]
If you change the CMakeList.txt, you need cmake and make the project again. Then it work!
