### ISSUE TITLE
Frame could not be processed

### ISSUE THREAD

**Issue by hpf9017** [jzhzhang/ROSEFusion#22]
Frame could not be processed

**Comment by fang-lai** [comment]
I also have the same problem

ubuntu 20.04 
rtx3060
cuda 11.7
opencv 4.5.5
eigen 3.3.9
sm_86

it mentioned that  "Frame could not be processed"

**Comment by jzhzhang** [comment]
@hpf9017 @fang-lai  Sorry for the late reply.  Please check the Opencv is built successfully with CUDA (turn on the ```opencv with CUDA``` option).  I also recommend you use the docker image if you are not sure your installation is correct.

**Comment by jzhzhang** [comment]
If you have further questions, feel free to reopen the issue.
