### ISSUE TITLE
OneDrive  rosefusion_docker.tar 文件下载下来无法解压,解压提示出错.

### ISSUE THREAD

**Issue by cfscn** [jzhzhang/ROSEFusion#23]
下载了很多次 都有该问题.

**Comment by cfscn** [comment]
@jzhzhang 大佬,您看下原因呢?

**Comment by jzhzhang** [comment]
你好，我们之前把docker镜像从google drive迁移到了One drive。过程中可能破坏了文件的完整。 目前的one drive里的镜像MD5为61a963894d79a77cd7a58eb37538be35，麻烦你确认一下不是下载的问题。 我们也会重新确认一下文件是否正确。

We have moved the docker image from google drive to one drive, and there may counter some mistakes while processing the image. The MD5 of image in one drive is 61a963894d79a77cd7a58eb37538be35. Please make sure the downloading is successfully finished. We will check whether the image is broken.

**Comment by cfscn** [comment]
![aaf090ac1a28548b9ccfb7b34d29526](https://user-images.githubusercontent.com/25838303/172980157-b0443f0f-95f4-427f-8b06-f9845179a345.png)
我对比了MD5 是正确的. 您看下是否文件完整被破坏了.

**Comment by cfscn** [comment]
@jzhzhang  请问下 我现在去哪里能下载 这个镜像呢？

**Comment by jzhzhang** [comment]
@cfscn  刚刚更新了one drive里的docker。 你可以重新在README里的链接里下载。 新的MD5码为2afeb0ac6793f650a72521655e4e3bbc

如果还有新的问题，欢迎随时联系我

**Comment by cfscn** [comment]
好了 下载下来能用了

**Comment by jzhzhang** [comment]
@cfscn  好的，感谢你的反馈
