### ISSUE TITLE
Can I use my depth camera to run in real time

### ISSUE THREAD

**Issue by y1131388949** [jzhzhang/ROSEFusion#25]
Can I use my depth camera to run in real time？

**Comment by jzhzhang** [comment]
Yes. ROSEFusion can run at 30 FPS with 640*480 depth seuqneces. We provide real captured sequences in [FastCaMO-Real](https://github.com/jzhzhang/ROSEFusion#fastcamo-dataset) and you can use off-the-shelf configuration files in ```camera_config```, ```controller_config``` and ```dataset_config``` to evaluate.
