### ISSUE TITLE
如何构造RGB-D数据集

### ISSUE THREAD

**Issue by zhuisa** [jzhzhang/ROSEFusion#27]
您好！请问一下应该如何构造自己的合成RGB-D数据集呢？是否有相关的教程或者博客可以推荐吗？十分感谢！论文中是如何生成FastCaMo-Synth数据集的呢？

**Comment by jzhzhang** [comment]
1）首先，你需要选择自己的场景和渲染器，我们使用的是replica的场景和渲染器。 
2）之后生成相机的轨迹，你可以自己手动采集，也可以用脚本生成，这个轨迹就是你数据集的ground truth。
3）渲染轨迹中每一帧的RGB和depth图像，并根据自己的需要添加运动模糊和噪声。

你可以参考 [Replica](https://github.com/facebookresearch/Replica-Dataset) 和 [TUM RGBD dataset](https://vision.in.tum.de/data/datasets/rgbd-dataset/file_formats)。
