### ISSUE TITLE
 When will the ASRO-DIO source code be released？

### ISSUE THREAD

**Issue by zhangzscn** [jzhzhang/ROSEFusion#29]

**Comment by jzhzhang** [comment]
It is currently undergoing patent review, and I believe it could be completed by June.

**Comment by zhangzscn** [comment]
Thank you. Looking forward to it

**Comment by zhangzscn** [comment]
any update？

**Comment by jzhzhang** [comment]
Sorry, the patent review is still ongoing. If you want to test your own sequences with our method, you can send them to my email. I will test them when I am free.

**Comment by zhangzscn** [comment]
Are there any plans to open source the ASRO-DIO algorithm? When is the open source expected？

**Comment by jzhzhang** [comment]
Still under patent review. I have shared ASRO-DIO code with some collaborators. If you need our code for your research, please send me an email at zhngjizh@gmail.com

**Comment by zhangzscn** [comment]
thank you.
