### ISSUE TITLE
I want to ask some questions about the examples of reconstructed images in your paper.

### ISSUE THREAD

**Issue by gfall-1407** [jzhzhang/ROSEFusion#32]
![image](https://github.com/jzhzhang/ROSEFusion/assets/45504189/75c08736-7e4d-449c-abaa-0711331d7285)
The result shown in the figure seems to have no ceiling. May I ask if you extracted the point cloud from TSDF, reconstructed it into a mesh model, and then clipped it?

**Comment by jzhzhang** [comment]
The shown figure is directly rendered with points cloud.  And yes, the ceiling is clipped for better visualization.

**Comment by gfall-1407** [comment]
How can I render the scene and trajectory together?

**Comment by jzhzhang** [comment]
We use [open3d](http://www.open3d.org/) to generate the cylinders to represent the trajectory and save them as meshs. Then we use [cloudcompare](https://www.danielgm.net/cc/) to render both the trajectory mesh and scene point cloud.
