### ISSUE TITLE
無法在docker裡display

### ISSUE THREAD

**Issue by KangKaiChen** [jzhzhang/ROSEFusion#34]
what():  Pangolin X11: Failed to open X display
Aborted (core dumped)

**Comment by jzhzhang** [comment]
You have to use x11 forwarding to forward the GUI interface to your PC.

**Comment by KangKaiChen** [comment]
> You have to use x11 forwarding to forward the GUI interface to your PC.
我已經嘗試解決剛剛的display問題了但是現在出現了OpenGL failed 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Pangolin X11: Failed to create an OpenGL context
Aborted (core dumped)
