### ISSUE TITLE
請問這是版本不兼容問題嘛 geforce 2070 && cuda 11.6 & opencv 4.5.1

### ISSUE THREAD

**Issue by KangKaiChen** [jzhzhang/ROSEFusion#35]
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.1) /home/kang/opencv-4.5.1/opencv_contrib-4.5.1/modules/cudev/include/opencv2/cudev/grid/detail/transform.hpp:264: error: (-217:Gpu API call) no kernel image is available for execution on the device in function 'call'

Aborted (core dumped)

**Comment by jzhzhang** [comment]
1. Please ensure that your OpenCV is built with CUDA support (e.g., WITH_CUDA=ON).
2. Ensure that your CUDA, driver, and OpenCV are compatible with each other.
