### ISSUE TITLE
About the ground truth trajectories

### ISSUE THREAD

**Issue by heyicheng-never** [jzhzhang/ROSEFusion#36]
I visualized the camera trajectory and orientation of sequence apartment_1 and noticed that the camera's pose seems to flip, for instance, the camera's Z-axis changes from initially pointing downwards to finally pointing upwards. This phenomenon does not seem to align with the camera movement inferred from the rendered RGB images.
![traj](https://github.com/jzhzhang/ROSEFusion/assets/57833516/2103c547-20bb-4b82-9966-3d98fd407039)
My approach to visualizing camera orientation involves converting the quaternion components qx, qy, qz, qw into a rotation matrix and then visualizing each column of this matrix.

**Comment by jzhzhang** [comment]
You are correct. The trajectory, designed for rendering RGBD images from the Replica simulator, may not conform to the typical camera coordination facing the positive z-axis. Nonetheless, it remains suitable for ATE evaluation, as ATE includes alignment operations essential for assessing positional errors.
