### ISSUE TITLE
如何利用自己的深度相机运行这个程序？

### ISSUE THREAD

**Issue by chen579** [jzhzhang/ROSEFusion#37]
您好，我现在也在使用Azure Kinect DK相机录制了对应的彩色图像与深度图像，并利用TUM数据集中的associate.py文件对于图像进行对齐操作，但是在运行过程中无法构建清晰的三维模型，即使不断的调整voxel_x/y/z这3个参数也无法得到一个较好的结果，请问如何解决这个问题呢

**Comment by jzhzhang** [comment]
能提供更多的结果么？ 比如重建的结果或者在线渲染的结果

**Comment by chen579** [comment]
您好，由于github上不方便上传动图，所以给邮箱zhngjizh@gmail.com发了邮件，对于问题进行了描述，本人邮箱chenjiawei_edu@163.com,非常感谢您的回复

**Comment by zhangzscn** [comment]
Kinect的深度图和彩色图要对齐，然后要修改配置文件的相机内参。
