### ISSUE TITLE
/usr/local/include/pangolin/gl/glsl.h: In member function ‘void pangolin::GlSlProgram::SetUniform(const string&, const pangolin::OpenGlMatrix&)’: /usr/local/include/pangolin/gl/glsl.h:728:5: error: ‘glUniformMatrix4fv’ was not declared in this scope

### ISSUE THREAD

**Issue by Darker-zq** [jzhzhang/ROSEFusion#4]
![2021-11-02 15-33-28 的屏幕截图](https://user-images.githubusercontent.com/73876465/139804754-db81f6ea-c6c5-45e4-bfcc-acd9a1f95714.png)

在我编译rosefusion时，make -j出现这个报错，请问是什么原因？

**Comment by jzhzhang** [comment]
这个问题应该是来自于Pangolin。 目前Pangolin的master branch似乎正在开发中。 你可以尝试稳定版本的[Pangolin](https://github.com/stevenlovegrove/Pangolin/tags)

This issue may relate to the version of Pangolin. Currently, the master branch is under development. You can try the stable versions of [Pangolin](https://github.com/stevenlovegrove/Pangolin/tags)

**Comment by jzhzhang** [comment]
If you have any further concerns, please feel free to reopen the issue
