### ISSUE TITLE
Inquiry About Depth Image Scanning and Camera Parameters in FastCaMo-Real Dataset

### ISSUE THREAD

**Issue by gfall-1407** [jzhzhang/ROSEFusion#40]
Hello, thank you for your outstanding work. 
I noticed that the depth data in the depth images scanned by the Azure Kinect DK appears as hexagons, but the depth images in the FastCaMo-Real dataset do not have this characteristic. Could you please explain how you scanned these images? Additionally, could you provide the parameters of the RGB and Depth cameras used when generating the FastCaMo-Real dataset?

**Comment by jzhzhang** [comment]
The API provided by the Kinect DK library includes functions to transform the hexagonal depth map into RGB images. For more details, check it out [here](https://microsoft.github.io/Azure-Kinect-Sensor-SDK/master/group___functions_gafacffb5f781a9c2df30d4a16241cd514.html#gafacffb5f781a9c2df30d4a16241cd514).

We use the RGB resolution mode of 2048×1536 and resize it to 640×480 (same operations as depth maps). The intrinsic matrix parameters can be found [here](https://github.com/jzhzhang/ROSEFusion/blob/main/camera_config/FastCaMo_camera.yaml).

**Comment by gfall-1407** [comment]
> The API provided by the Kinect DK library includes functions to transform the hexagonal depth map into RGB images. For more details, check it out [here](https://microsoft.github.io/Azure-Kinect-Sensor-SDK/master/group___functions_gafacffb5f781a9c2df30d4a16241cd514.html#gafacffb5f781a9c2df30d4a16241cd514).
> 
> We use the RGB resolution mode of 2048×1536 and resize it to 640×480 (same operations as depth maps). The intrinsic matrix parameters can be found [here](https://github.com/jzhzhang/ROSEFusion/blob/main/camera_config/FastCaMo_camera.yaml).

Thank you very much for your detailed response.
