### ISSUE TITLE
Visualization issues

### ISSUE THREAD

**Issue by Darker-zq** [jzhzhang/ROSEFusion#5]
I downloaded the image that you uploaded in docker. And downloaded the small size synthesis example than you uploaded. But there was no visual interface when i run ./ROSEFsuion  example_camera_config.yaml example_data_config.yaml example_controller_config.yaml. The program did not crash and 'example.txt' generated successfully .
What caused the visual interface not to appear?Whan should i do?
thanks!
![image](https://user-images.githubusercontent.com/73876465/142375738-ba360312-f792-4352-bbd6-2e7d6837b78b.png)

**Comment by abc619539082** [comment]
you should check your example_data_config.yaml to change the result path to yours

**Comment by Darker-zq** [comment]
thanks your reply.
the new issues was occured.when i run it again.
![image](https://user-images.githubusercontent.com/73876465/142416775-b6cd10e7-54c2-4b09-83f5-d7690c3dbd2a.png)
I'm sorry to disturb you.

**Comment by jzhzhang** [comment]
@Darker-zq  Thanks for your interest and @abc619539082  thanks for your kind help.

The visual interface (rendering surface) is disabled because the docker is not designed for the GUI output. If you want to visualize the GUI of ROSEFusion in docker, please try the following steps:
1. Change the "render_surface" of controller.yaml to "1"
2. Bind the GUI output to some program.  Here is a quick [reference](https://stackoverflow.com/questions/16296753/can-you-run-gui-applications-in-a-linux-docker-container).

**Comment by Darker-zq** [comment]
thank yours answer。 Why the frame cloud not be processed? The .ply file is not have element vertex.
![image](https://user-images.githubusercontent.com/73876465/142564182-82fe9e02-1fd7-40d3-bcaf-3b6f62d9140d.png)

**Comment by jzhzhang** [comment]
This may relate to some of your changes to configuration files. Have you tried to directly use the ```run_example.sh``` or ```run_stairwell.sh``` in ```/home/code/ROSEFusion-main/build```?  These are prepared scripts to run the ROSEFusion.

**Comment by Darker-zq** [comment]
yes, I had been ran the run_example.sh and  run_stairwell.sh. And the results were still the same.

**Comment by jzhzhang** [comment]
Can you give me more details about your hardware and modifications?  And did the trajectory results are normal?

**Comment by Darker-zq** [comment]
I downloaded the docker file and did not make any changes. I checked the path in the configuration file and it was consistent. At the same time, the point cloud was still not processed after trying to run the .sh file.
The host computer used ubuntu18.04 system and the GPU is nvidia  GeForce RTX 3090.
The  trajectory results are still incorrect. The example.txt and stairwell.txt only have [0 0 0 0 0 1].

**Comment by zhanghua7099** [comment]
https://github.com/jzhzhang/ROSEFusion/issues/5#issuecomment-973698135

Same problems.

I didn't use ROSEFusion via Docker, but occur the same errors. The trajectory and mesh file were not saved properly.
My GPU is RTX 3090. 
```
Frame could not be processed
n:2
Frame could not be processed
n:3
Frame could not be processed
n:4
Frame could not be processed
n:5
Frame could not be processed
n:6
Frame could not be processed
n:7
```

**Comment by Darker-zq** [comment]
@zhanghua7099  please check the architecture in the L22 of /home/code/ROSEFusion-main/CMakeList.txt is compatible with your own graphics card. If not, change the sm_75 and compute_75 to sm_86 and compute_86, then rebuild the ROSEFusion.
It is worth noting that this is just a suggestion of mine, I did this in docker but still did not generate trajectory and point cloud。

**Comment by jcyhcs** [comment]
@Darker-zq  @jzhzhang 
i also got the same error with you,which said "Frame could not be processed",oh,what's the problem?
please help me!

**Comment by jzhzhang** [comment]
@jcyhcs @Darker-zq @zhanghua7099  Sorry for all the trouble. 

I have tested the code on 2080 SUPER, 3080Ti and Quadro T1000 without reproducing the same bug. I will further check the code and the environment.

**Comment by jcyhcs** [comment]
@jzhzhang  
thx, then my enviroment is:
Quadro P4000: Driver Version: 460.91.03    CUDA Version: 11.2
opencv:4.5.1
this problem boring me,so please help!

**Comment by Darker-zq** [comment]
for the problem of "Frame could not be processed", please check the architecture in the L22 of /home/code/ROSEFusion-main/CMakeList.txt is compatible with your own graphics card. If not, change the sm_75 and compute_75 to sm_xx and compute_xx, then rebuild the ROSEFusion. The cuda arch(value of xx)could Inquired on [https://developer.nvidia.com/cuda-gpus](https://developer.nvidia.com/cuda-gpus)

**Comment by jzhzhang** [comment]
@jcyhcs @Darker-zq  Great！Thanks for your interest in our project.
