### ISSUE TITLE
can use for outdoor scene reconstruction?

### ISSUE THREAD

**Issue by jcyhcs** [jzhzhang/ROSEFusion#6]
hi,professor:
if i have a RGBD camera, this method can use for outdoor  static scene reconstruction?

**Comment by jzhzhang** [comment]
Thanks for your interest. 

Our method is designed for indoor scenes.  In the outdoor environment, the RGB-D cameras may suffer from complex lighting conditions. And also the TSDF volume may take up more memory than your GPU can provide.
