### ISSUE TITLE
Cannot run example

### ISSUE THREAD

**Issue by rlczddl** [jzhzhang/ROSEFusion#8]
Hi,my env is: ubuntu18.04、cuda11.1、opencv4.4 with cuda and i can build the ROSEFusion exe on my machine,but I meet the "Frame could not be processed" problem. Here is the config file:
![image](https://user-images.githubusercontent.com/21055131/145966746-b56c78d7-5158-4cee-b751-a092fe7814da.png)
![image](https://user-images.githubusercontent.com/21055131/145966803-5f1efcd1-1e02-4a40-bc67-30c8bf29c31f.png)
![image](https://user-images.githubusercontent.com/21055131/145966881-0f62b2a5-53c0-4256-9a42-5ab51e0892e2.png)

Any suggestions?

**Comment by jzhzhang** [comment]
Please check if your CUDA architecture is compatible with the [CMakeLists.txt](https://github.com/jzhzhang/ROSEFusion/blob/02a847994c835bf6381201bd91c755fd2ae4dc76/CMakeLists.txt#L22). 

The previous [issue#5](https://github.com/jzhzhang/ROSEFusion/issues/5#issuecomment-979943151) may relate to your problem.

**Comment by rlczddl** [comment]
@jzhzhang OK，I see.
