### ISSUE TITLE
Data Preparation about  ./seq_gen  <.yaml>

### ISSUE THREAD

**Issue by Darker-zq** [jzhzhang/ROSEFusion#9]
I'm sorry to disturb you.
An error occurred when I ran ./seq_gen.
I recorded my own data by using Azure Kinect DK.but these data cannot be converted into .seq format files.
The error is as follows：
![image](https://user-images.githubusercontent.com/73876465/146188680-2976259b-ef8b-48ab-a200-f78b54d4dd67.png)

My data as follows:

![image](https://user-images.githubusercontent.com/73876465/146188823-5e0b60ff-a4c5-429a-87e5-36f18a9f8e5a.png)

**color**

![image](https://user-images.githubusercontent.com/73876465/146188909-38249cc8-6e25-4980-9b86-92cf1dbb042a.png)

**depth**

![image](https://user-images.githubusercontent.com/73876465/146188932-9679cd9e-9f5a-451f-8992-6430c0e57fb3.png)

**sequence_information.yaml**

![image](https://user-images.githubusercontent.com/73876465/146189253-a015b59e-b29c-4633-8cb0-a0c0e72a9e14.png)

**associations.txt**
![image](https://user-images.githubusercontent.com/73876465/146188973-6c3d9cd3-2883-425b-8f75-6e516f9fca07.png)

I could convert the data that you provided to .seq format successfully .
How can I solve it, thank you very much.

**Comment by jzhzhang** [comment]
Please check your depth maps and make sure they are stored as 16-bit integers.

**Comment by Darker-zq** [comment]
thanks for your answer.
The actual problem is that I made a basic mistake that my sequence_information.yaml(402test_2.yaml)  starts with a number.
